### PR TITLE
Some fixes for proper working in python3

### PR DESCRIPTION
**Pull request by awmackowiak**

### CODE REVIEW

**Comment by powdahound** [comment]
Thanks! What's the reasoning behind the cluster change in redis.conf?

**Comment by awmackowiak** [comment]
Hey, because i got single instance on my environment and i don't have cluster instances. So i got an error:
`Mar 03 09:56:33 machine collectd[142498]: Unhandled python exception in read callback: ValueError: invalid literal for int() with base 10: 'ERR This instance has cluster support disabled\r'`
`127.0.0.1:6379> cluster info
ERR This instance has cluster support disabled`
because in `redis_info.py on line 183` the value of cluster is setup to `True`
So I thought the bets way to disable it will be in configuration.

**Comment by powdahound** [comment]
I see, thanks. Unfortunately it's now out of sync with the comment above it ("Cluster mode expected by default"). Given that it's unrelated to the Python 3 changes I think it's best to revert this change for the PR and you can keep your own local configuration set to not use cluster mode.

**Comment by awmackowiak** [comment]
I was bring back hashed Cluster parameter in config as you wish :)

**Comment by powdahound** [comment]
Thank you!

**Pull request merged**
